-- Version 6.0.2
SELECT ISNULL(dbo.PROJECT.PROJ_ID,0) AS ProjectId
     , (ISNULL(dbo.PROJECT.PROJ_SHORT_NAME,'') + ' - ' + 
      ISNULL((SELECT TOP 1 dbo.PROJWBS.WBS_NAME
      FROM dbo.PROJWBS
      WHERE dbo.PROJWBS.PROJ_ID = dbo.PROJECT.PROJ_ID),'')) AS ProjectName
FROM dbo.PROJECT
WHERE dbo.PROJECT.DELETE_SESSION_ID IS NULL
