/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.core.js";const __meta__={id:"data.xml",name:"XML",category:"framework",depends:["core"],hidden:!0};!function(e){var t=window.kendo,r=Array.isArray,n=e.isPlainObject,a=e.map,i=e.each,o=e.extend,d=t.getter,f=t.Class.extend({init:function(e){var d=this,f=e.total,l=e.model,s=e.parse,u=e.errors,p=e.serialize,c=e.data;if(l){if(n(l)){var m=e.modelBase||t.data.Model;l.fields&&i(l.fields,(function(e,r){n(r)&&r.field?t.isFunction(r.field)||(r=o(r,{field:d.getter(r.field)})):r={field:d.getter(r)},l.fields[e]=r}));var h=l.id;if(h){var x={};x[d.xpathToMember(h,!0)]={field:d.getter(h)},l.fields=o(x,l.fields),l.id=d.xpathToMember(h)}l=m.define(l)}d.model=l}if(f&&("string"==typeof f?(f=d.getter(f),d.total=function(e){return parseInt(f(e),10)}):"function"==typeof f&&(d.total=f)),u&&("string"==typeof u?(u=d.getter(u),d.errors=function(e){return u(e)||null}):"function"==typeof u&&(d.errors=u)),c&&("string"==typeof c?(c=d.xpathToMember(c),d.data=function(e){var t,n=d.evaluate(e,c);return n=r(n)?n:[n],d.model&&l.fields?(t=new d.model,a(n,(function(e){if(e){var r,n={};for(r in l.fields)n[r]=t._parse(r,l.fields[r].field(e));return n}}))):n}):"function"==typeof c&&(d.data=c)),"function"==typeof s){var g=d.parse;d.parse=function(e){var t=s.call(d,e);return g.call(d,t)}}"function"==typeof p&&(d.serialize=p)},total:function(e){return this.data(e).length},errors:function(e){return e?e.errors:null},serialize:function(e){return e},parseDOM:function(e){var t,n,a,i,o,d,f,l={},s=e.attributes,u=s.length;for(f=0;f<u;f++)l["@"+(d=s[f]).nodeName]=d.nodeValue;for(n=e.firstChild;n;n=n.nextSibling)3===(a=n.nodeType)||4===a?l["#text"]=n.nodeValue:1===a&&(t=this.parseDOM(n),o=l[i=n.nodeName],r(o)?o.push(t):o=undefined!==o?[o,t]:t,l[i]=o);return l},evaluate:function(e,t){for(var n,a,i,o,d,f=t.split(".");n=f.shift();)if(e=e[n],r(e)){for(a=[],t=f.join("."),d=0,i=e.length;d<i;d++)o=this.evaluate(e[d],t),o=r(o)?o:[o],a.push.apply(a,o);return a}return e},parse:function(t){var r,n,a={};return r=t.documentElement||e.parseXML(t).documentElement,n=this.parseDOM(r),a[r.nodeName]=n,a},xpathToMember:function(e,t){return e?(e=e.replace(/^\//,"").replace(/\//g,".")).indexOf("@")>=0?e.replace(/\.?(@.*)/,t?"$1":'["$1"]'):e.indexOf("text()")>=0?e.replace(/(\.?text\(\))/,t?"#text":'["#text"]'):e:""},getter:function(e){return d(this.xpathToMember(e),!0)}});e.extend(!0,t.data,{XmlDataReader:f,readers:{xml:f}})}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.data.xml.js.map
