/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.core.js";import"./kendo.drawing.js";import"./kendo.color.js";kendo.pdf=kendo.pdf||{},kendo.pdf.supportsDeflate=function(){return window.pako&&"function"==typeof window.pako.deflate},kendo.pdf.deflate=function(e){return window.pako.deflate(e)},window.kendo.jQuery,function(e){kendo.PDFMixin={extend:function(e){e.events.push("pdfExport"),e.options.pdf=this.options,e.saveAsPDF=this.saveAsPDF,e._drawPDF=this._drawPDF,e._drawPDFShadow=this._drawPDFShadow},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:!1,landscape:!1,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator v."+kendo.version,date:null},saveAsPDF:function(){var o=new e.Deferred,r=o.promise(),n={promise:r};if(!this.trigger("pdfExport",n)){var t=this.options.pdf;return t.multiPage=t.multiPage||t.allPages,this._drawPDF(o).then((function(e){return kendo.drawing.exportPDF(e,t)})).done((function(e){kendo.saveAs({dataURI:e,fileName:t.fileName,proxyURL:t.proxyURL,forceProxy:t.forceProxy,proxyTarget:t.proxyTarget}),o.resolve()})).fail((function(e){o.reject(e)})),r}},_drawPDF:function(o){var r=new e.Deferred;return kendo.drawing.drawDOM(this.wrapper).done((function(e){var n={page:e,pageNumber:1,progress:1,totalPages:1};o.notify(n),r.resolve(n.page)})).fail((function(e){r.reject(e)})),r},_drawPDFShadow:function(o,r){o=o||{};var n=this.wrapper,t=e("<div class='k-pdf-export-shadow'>");o.width&&t.css({width:o.width,overflow:"visible"}),n.before(t),t.append(o.content||n.clone(!0,!0));var a=e.Deferred();return setTimeout((function(){kendo.drawing.drawDOM(t,r).always((function(){t.remove()})).then((function(){a.resolve.apply(a,arguments)})).fail((function(){a.reject.apply(a,arguments)})).progress((function(){a.progress.apply(a,arguments)}))}),15),a.promise()}}}(window.kendo.jQuery);const __meta__={id:"pdf",name:"PDF export",description:"PDF Generation framework",mixin:!0,category:"framework",depends:["core","drawing"]};export{__meta__};
//# sourceMappingURL=kendo.pdf.js.map
