/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import{c as coreExport,G as GRADIENTS,s as services$1,h as hasOwnProperty,P as Point,B as Box,m as mousewheelDelta}from"./kendo.charts.cmn.chunk.js";import"./kendo.drawing.js";const __meta__={id:"dataviz.core",name:"Core",description:"The DataViz core functions",category:"dataviz",depends:["core","drawing","charts.cmn.chunk"],hidden:!0};window.kendo.dataviz=window.kendo.dataviz||{},kendo.deepExtend(kendo.dataviz,kendo.deepExtend({},coreExport)),kendo.dataviz.Gradients=GRADIENTS;const $=kendo.jQuery;let dataviz=kendo.dataviz,draw=kendo.drawing,services=services$1;for(let e in coreExport)hasOwnProperty(e)&&(dataviz[e]=coreExport[e]);dataviz.SASS_THEMES=["sass","default-v2","bootstrap-v4","material-v2"],dataviz.ExportMixin={extend:function(e,t){if(!e.exportVisual)throw new Error("Mixin target has no exportVisual method defined.");e.exportSVG=this.exportSVG,e.exportImage=this.exportImage,e.exportPDF=this.exportPDF,t||(e.svg=this.svg,e.imageDataURL=this.imageDataURL)},exportSVG:function(e){return draw.exportSVG(this.exportVisual(),e)},exportImage:function(e){return draw.exportImage(this.exportVisual(e),e)},exportPDF:function(e){return draw.exportPDF(this.exportVisual(),e)},svg:function(){if(draw.svg.Surface)return draw.svg.exportGroup(this.exportVisual());throw new Error("SVG Export failed. Unable to export instantiate kendo.drawing.svg.Surface")},imageDataURL:function(){if(!kendo.support.canvas)return null;if(draw.canvas.Surface){var e=$("<div />").css({display:"none",width:this.element.width(),height:this.element.height()}).appendTo(document.body),t=new draw.canvas.Surface(e[0]);t.draw(this.exportVisual());var a=t._rootElement.toDataURL();return t.destroy(),e.remove(),a}throw new Error("Image Export failed. Unable to export instantiate kendo.drawing.canvas.Surface")}},services.IntlService.register({format:function(e){return kendo.format.apply(null,[e].concat(Array.prototype.slice.call(arguments,1)))},toString:kendo.toString,parseDate:kendo.parseDate,firstDay:function(){return kendo.culture().calendars.standard.firstDay}}),services.TemplateService.register({compile:kendo.template}),dataviz.inArray=function(e,t){if(t)return-1!==t.indexOf(e)},dataviz.Point2D=Point,dataviz.Box2D=Box,dataviz.mwDelta=function(e){return mousewheelDelta(e.originalEvent)};var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.dataviz.core.js.map
