/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.data.js";const __meta__={id:"data.signalr",name:"SignalR",category:"framework",depends:["data"],hidden:!0};!function(t){var e=window.kendo,n=e.isFunction;function r(t){return t&&n(t.done)&&n(t.fail)}function o(t){return t&&n(t.then)&&n(t.catch)}var i=e.data.RemoteTransport.extend({init:function(t){var n=t&&t.signalr?t.signalr:{},i=n.promise;if(!i)throw new Error('The "promise" option must be set.');if(!r(i)&&!o(i))throw new Error('The "promise" option must be a Promise.');this.promise=i;var a=n.hub;if(!a)throw new Error('The "hub" option must be set.');if("function"!=typeof a.on||"function"!=typeof a.invoke)throw new Error('The "hub" option is not a valid SignalR hub proxy.');this.hub=a,e.data.RemoteTransport.fn.init.call(this,t)},push:function(t){var e=this.options.signalr.client||{};e.create&&this.hub.on(e.create,t.pushCreate),e.update&&this.hub.on(e.update,t.pushUpdate),e.destroy&&this.hub.on(e.destroy,t.pushDestroy)},_crud:function(n,i){var a=this.hub,s=this.promise,u=this.options.signalr.server;if(!u||!u[i])throw new Error(e.format('The "server.{0}" option must be set.',i));var h=[u[i]],d=this.parameterMap(n.data,i);t.isEmptyObject(d)||h.push(d),r(s)?s.done((function(){a.invoke.apply(a,h).done(n.success).fail(n.error)})):o(s)&&s.then((function(){a.invoke.apply(a,h).then(n.success).catch(n.error)}))},read:function(t){this._crud(t,"read")},create:function(t){this._crud(t,"create")},update:function(t){this._crud(t,"update")},destroy:function(t){this._crud(t,"destroy")}});t.extend(!0,e.data,{transports:{signalr:i}})}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.data.signalr.js.map
