/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.html.base.js";import"./kendo.icons.js";const __meta__={id:"html.chip",name:"Html.Chip",category:"web",description:"HTML rendering utility for Kendo UI for jQuery.",depends:["html.base","icons"],features:[]};!function(a){var e=window.kendo,s=e.html.HTMLBase,t=s.extend({init:function(a,e){s.fn.init.call(this,a,e),this._wrapper()},options:{name:"HTMLChip",size:"medium",rounded:"medium",fillMode:"solid",themeColor:"base",attr:{},icon:"",iconClass:"",iconAttr:{},removable:!1,removableAttr:{},removeIcon:"x-circle",removeIconClass:"",content:"",text:"",actions:[],stylingOptions:["size","rounded","fillMode","themeColor"]},_wrapper:function(){var s=this,t=s.options;t.text=t.text||t.label,s.wrapper=s.element.wrap("<div class='k-chip'></div>").parent().attr(t.attr),s._addClasses(),t.icon?s.wrapper.prepend(a(e.ui.icon({icon:t.icon,size:"small",iconClass:"k-chip-icon"+(t.iconClass?` ${t.iconClass}`:"")})).attr(t.iconAttr)):t.iconClass?s.wrapper.prepend(a("<span class='"+t.iconClass+"'></span>").attr(t.iconAttr)):t.avatarClass&&s.wrapper.prepend(a("<span class='k-chip-avatar k-avatar k-avatar-md k-avatar-solid k-avatar-solid-primary k-rounded-full "+t.avatarClass+"'></span>").attr(t.iconAttr)),s.element.addClass("k-chip-content"),t.text&&s.element.html('<span class="k-chip-label">'+t.text+"</span>"),!1===t.visible&&s.wrapper.addClass("k-hidden"),!0===t.selected&&s.wrapper.addClass("k-selected"),!1===t.enabled&&s.wrapper.addClass("k-disabled"),(t.actions&&t.actions.length>0||t.removable)&&s._actions()},_actions:function(){var s=this,t=s.options;if(s.actionsWrapper=a("<span class='k-chip-actions'></span>"),s.actionsWrapper.appendTo(s.wrapper),t.actions&&t.actions.length>0)for(var n=0;n<t.actions.length;n++){var i=t.actions[n];s.actionsWrapper.append(a(`<span class='k-chip-action ${i.iconClass?i.iconClass:""}'>${e.ui.icon({icon:i.icon,size:"small"})}</span>`).attr(i.attr?i.attr:{}))}t.removable&&s.actionsWrapper.append(a(`<span class='k-chip-action k-chip-remove-action'>${e.ui.icon({icon:t.removeIcon,size:"small"})}</span>`).attr(t.removableAttr))}});a.extend(e.html,{renderChip:function(e,s){return e&&!a.isPlainObject(e)||(s=e,e=a("<span></span>")),new t(e,s).html()},HTMLChip:t}),e.cssProperties.registerPrefix("HTMLChip","k-chip-"),e.cssProperties.registerValues("HTMLChip",[{prop:"rounded",values:e.cssProperties.roundedValues.concat([["full","full"]])}])}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.html.chip.js.map
