/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.core.js";import"./kendo.icons.js";const __meta__={id:"avatar",name:"Avatar",category:"web",description:"The Avatar component represents an icon, text, or image rendered in a styled container.",depends:["core"]};!function(t){var e=window.kendo,n=e.ui.Widget,r=".k-icon,.k-svg-icon",i="k-avatar",s="k-avatar-bordered",a="icon",o="image",p="text",l=n.extend({init:function(t,e){e=e||{},n.fn.init.call(this,t,e),this._fromMarkup(),this._wrapper(),this._markupContent&&this._markupContent.length>0?this._contentFromMarkup():this._content()},options:{name:"Avatar",alt:null,border:!1,className:null,fillMode:"solid",icon:null,image:null,rounded:"full",size:"medium",style:null,text:null,themeColor:"primary",type:p},events:[],setOptions:function(e){var r=this.options,i=this.wrapper,a=t.extend({},r,e);n.fn.setOptions.call(this,e),a[a.type]||(r=this._optionsFromWrapper(r)),!1===a.border&&i.removeClass(s),i.empty(),this.options=r,this._wrapper(),this._content()},_content:function(){var n,r=this.wrapper.find("> span"),i=this.options,s=i.type;s===a?n=t(e.html.renderIcon({icon:i.icon})):s===o?(n=t("<img src='"+i.image+"'>"),i.alt&&n.attr("alt",i.alt)):s===p&&(n=t("<span>"+i.text+"</span>")),r.append(n)},_contentFromMarkup:function(){this.wrapper.find("> span").first().append(this._markupContent)},_fromMarkup:function(){var t,e,n=this.element,i=this.options;n.children().slice(1).remove(),t=n.children("img"),e=n.children(r),t.length>0?(i.type=o,this._markupContent=t.first()):e.length>0?(i.type=a,this._markupContent=e.first()):n.children().length>0&&(i.type=p,this._markupContent=n.children())},_optionsFromWrapper:function(t){var e,n=this.wrapper;return t.type===p?t.text=n.text().trim():t.type===a?n.find(r).attr("class").split(/\s+/).forEach((function(e){0===e.indexOf("k-i-")?t.icon=e.substring(4):0===e.indexOf("k-svg-i-")&&(t.icon=e.replace(/^k-svg-i-/,""))})):t.type===o&&(e=n.find("img"),t.image=e.attr("src"),e.attr("alt")&&(t.alt=e.attr("alt"))),t},_wrapper:function(){var e=this.element,n=this.options,r=t("<span>");this.wrapper=e,e.addClass(i),this._applyCssClasses(),n.border&&e.addClass(s),n.style&&e.css(n.style),n.className&&e.addClass(n.className),r.addClass(i+"-"+n.type),e.prepend(r)}});e.cssProperties.registerPrefix("Avatar","k-avatar-"),e.cssProperties.registerValues("Avatar",[{prop:"rounded",values:e.cssProperties.roundedValues.concat([["full","full"]])}]),e.ui.plugin(l)}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.avatar.js.map
