/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.view.js";const __meta__={id:"pane",name:"Pane",category:"web",description:"Pane",depends:["view"],hidden:!0};!function(i){var e=window.kendo,t=e.roleSelector,n=e.ui,o=n.Widget,a=e.ViewEngine,r=e.View,s=i.extend,l="navigate",d="viewShow",c="sameViewRequested",h=e.support.mobileOS,p=h.ios&&!h.appMode&&h.flatVersion>=700,v="k-pane",u="k-pane-wrapper",w="k-collapsible-pane",f=o.extend({init:function(i,t){var n=this;o.fn.init.call(n,i,t),t=n.options,(i=n.element).addClass(v),n.options.collapsible&&i.addClass(w),this.history=[],this.historyCallback=function(i,e,t){var o=n.transition;return n.transition=null,p&&t&&(o="none"),n.viewEngine.showView(i,o,e)},this._historyNavigate=function(i){if("#:back"===i){if(1===n.history.length)return;n.history.pop(),i=n.history[n.history.length-1]}else i instanceof r&&(i=""),n.history.push(i);n.historyCallback(i,e.parseQueryStringParams(i))},this._historyReplace=function(i){var t=e.parseQueryStringParams(i);n.history[n.history.length-1]=i,n.historyCallback(i,t)},n.viewEngine=new a(s({},{container:i,transition:t.transition,modelScope:t.modelScope,rootNeeded:!t.initial,serverNavigation:t.serverNavigation,remoteViewURLPrefix:t.root||"",layout:t.layout,showStart:function(){n.closeActiveDialogs()},after:function(){},viewShow:function(i){n.trigger(d,i)},loadStart:function(){},loadComplete:function(){},sameViewRequested:function(){n.trigger(c)},viewTypeDetermined:function(i){i.remote&&n.options.serverNavigation||n.trigger(l,{url:i.url})}},this.options.viewEngine)),this._setPortraitWidth(),e.onResize((function(){n._setPortraitWidth()}))},closeActiveDialogs:function(){this.element.find(t("actionsheet popover modalview")).filter(":visible").each((function(){e.widgetInstance(i(this),n).close()}))},navigateToInitial:function(){var i=this.options.initial;return i&&this.navigate(i),i},options:{name:"Pane",portraitWidth:"",transition:"",layout:"",collapsible:!1,initial:null,modelScope:window},events:[l,d,c],append:function(i){return this.viewEngine.append(i)},destroy:function(){var i=this;o.fn.destroy.call(i),i.viewEngine&&i.viewEngine.destroy()},navigate:function(i,e){i instanceof r&&(i=i.id),this.transition=e,this._historyNavigate(i)},replace:function(i,e){i instanceof r&&(i=i.id),this.transition=e,this._historyReplace(i)},view:function(){return this.viewEngine.view()},_setPortraitWidth:function(){this.options.portraitWidth&&this.element.css("width",undefined)}});f.wrap=function(i,n){i.is(t("view"))||(i=i.wrap("<div data-"+e.ns+'role="view" data-stretch="true"></div>').parent());var o=i.wrap('<div class="'+u+' k-widget"><div></div></div>').parent(),a=new f(o,n);return a.navigate(""),a},e.Pane=f}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.pane.js.map
