/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.core.js";import"./kendo.data.js";import{E as ExcelExporter,T as TemplateService}from"./kendo.ooxml.cmn.chunk.js";import"./kendo.ooxml.js";!function(e,t){var o=e.extend;let a=t.ConvertClass(ExcelExporter);TemplateService.register({compile:t.template}),t.ExcelExporter=t.Class.extend({init:function(e){this.options=e;var a=e.dataSource;if(a instanceof t.data.DataSource){a.filter()||(a.options.filter=void 0),this.dataSource=new a.constructor(o({},a.options,{page:e.allPages?0:a.page(),filter:a.filter(),pageSize:e.allPages||e.groupPaging?a.total():a.pageSize()||a.total(),sort:a.sort(),group:a.group(),aggregate:a.aggregate(),isExcelExportRequest:!0}));var r=a.data();if(r.length>0){if(e.hierarchy)for(var i=0;i<r.length;i++)!1!==r[i].expanded&&void 0!==r[i].expanded||(r[i].expanded=!0,r[i].shouldRestoreExpandedState=!0);this.dataSource._data=r;var n=this.dataSource.transport;a._isServerGrouped()&&n.options&&n.options.data&&(n.options.data=null)}}else this.dataSource=t.data.DataSource.create(a)},_hierarchy:function(){var e=this.options.hierarchy,t=this.dataSource;if(e&&t.level){e={itemLevel:function(e){return t.level(e)}};for(var o,a=t.view(),r=0,i=0;i<a.length;i++)(o=t.level(a[i]))>r&&(r=o);e.depth=r+1}else e=!1;return{hierarchy:e}},_restoreExpandedState:function(){var e=this.options,t=e.dataSource.data(),o=e.hierarchy;if(t.length>0&&o)for(var a=0;a<t.length;a++)t[a].shouldRestoreExpandedState&&(t[a].expanded=!1,delete t[a].shouldRestoreExpandedState)},workbook:function(){return e.Deferred(function(e){this.dataSource.fetch().then(function(){var t=new a(o({},this.options,this._hierarchy(),{data:this.dataSource.view(),groups:this.dataSource.group(),aggregates:this.dataSource.aggregates()})).workbook();e.resolve(t,this.dataSource.view())}.bind(this))}.bind(this)).promise()}}),window.kendo.excel=window.kendo.excel||{},window.kendo.excel.ExcelExporter=a,window.kendo.excel.TemplateService=TemplateService}(kendo.jQuery,kendo),function(e,t){t.ExcelMixin={extend:function(t){t.events.push("excelExport"),t.options.excel=e.extend(t.options.excel,this.options),t.saveAsExcel=this.saveAsExcel},options:{proxyURL:"",allPages:!1,filterable:!1,fileName:"Export.xlsx",collapsible:!1},saveAsExcel:function(e){var o=this.options.excel||{},a=new t.ExcelExporter({columns:this.columns,dataSource:this.dataSource,allPages:o.allPages,filterable:o.filterable,hierarchy:o.hierarchy,collapsible:o.collapsible});a.workbook().then(function(r,i){if(!this.trigger("excelExport",{workbook:r,data:i})){var n=new t.ooxml.Workbook(r);n.options||(n.options={}),n.options.skipCustomHeight=!0,n.toDataURLAsync().then((function(i){t.saveAs({dataURI:i,fileName:r.fileName||o.fileName,proxyURL:o.proxyURL,forceProxy:o.forceProxy}),a._restoreExpandedState&&a._restoreExpandedState(),e&&e.resolve()}))}}.bind(this))}}}(kendo.jQuery,kendo);const __meta__={id:"excel",name:"Excel export",category:"framework",advanced:!0,mixin:!0,depends:["data","ooxml","ooxml.cmn.chunk"]};export{__meta__};
//# sourceMappingURL=kendo.excel.js.map
