/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
const __meta__={id:"file-saver.cmn.chunk",name:"FileSaverCmnChunk",category:"web",description:"A reusable outputed chunk of code",depends:[],hidden:!0,chunk:!0};function saveAs(e,t,r){void 0===r&&(r={});var o=postToProxy;if(r.forceProxy&&!r.proxyURL)throw new Error("No proxyURL is set, but forceProxy is true");r.forceProxy||(canDownload()&&(o=saveAsDataURI),navigator.msSaveBlob&&(o=saveAsBlob)),o(e,t,r)}var anchor=function(){return document.createElement("a")},canDownload=function(){return"download"in anchor()};function saveAsBlob(e,t){var r=e;if("string"==typeof e){for(var o=e.split(";base64,"),a=o[0],n=atob(o[1]),c=new Uint8Array(n.length),i=0;i<n.length;i++)c[i]=n.charCodeAt(i);r=new Blob([c.buffer],{type:a})}navigator.msSaveBlob(r,t)}function saveAsDataURI(e,t){var r=e;window.Blob&&e instanceof Blob&&(r=URL.createObjectURL(e));var o=anchor();o.download=t,o.href=r;var a=document.createEvent("MouseEvents");a.initMouseEvent("click",!0,!1,window,0,0,0,0,0,!1,!1,!1,!1,0,null),o.dispatchEvent(a),setTimeout((function(){return URL.revokeObjectURL(r)}))}function postToProxy(e,t,r){if(r.proxyURL){var o=document.createElement("form");o.setAttribute("action",r.proxyURL),o.setAttribute("method","POST"),o.setAttribute("target",r.proxyTarget||"_self");var a=r.proxyData||{};a.fileName=t;var n=e.split(";base64,");for(var c in a.contentType=n[0].replace("data:",""),a.base64=n[1],a)if(a.hasOwnProperty(c)){var i=document.createElement("input");i.setAttribute("type","hidden"),i.setAttribute("name",c),i.setAttribute("value",a[c]),o.appendChild(i)}document.body.appendChild(o),o.submit(),document.body.removeChild(o)}}var KEY_STR="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",fromCharCode=String.fromCharCode;function encodeBase64(e){for(var t,r,o,a,n,c,i,d=encodeUTF8(e),s="",u=0;u<d.length;)a=(t=d.charCodeAt(u++))>>2,n=(3&t)<<4|(r=d.charCodeAt(u++))>>4,c=(15&r)<<2|(o=d.charCodeAt(u++))>>6,i=63&o,isNaN(r)?c=i=64:isNaN(o)&&(i=64),s=s+KEY_STR.charAt(a)+KEY_STR.charAt(n)+KEY_STR.charAt(c)+KEY_STR.charAt(i);return s}function encodeUTF8(e){for(var t="",r=0;r<e.length;r++){var o=e.charCodeAt(r);o<128?t+=fromCharCode(o):o<2048?(t+=fromCharCode(192|o>>>6),t+=fromCharCode(128|63&o)):o<65536&&(t+=fromCharCode(224|o>>>12),t+=fromCharCode(128|o>>>6&63),t+=fromCharCode(128|63&o))}return t}export{saveAs as s};export{__meta__};
//# sourceMappingURL=kendo.file-saver.cmn.chunk.js.map
