/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
import"./kendo.html.base.js";import"./kendo.icons.js";const __meta__={id:"html.button",name:"Html.Button",category:"web",description:"HTML rendering utility for Kendo UI for jQuery.",depends:["html.base","icons"],features:[]};!function(e){var t=window.kendo,n=t.html.HTMLBase,s="k-button-icon",i=n.extend({init:function(e,t){var s=this;n.fn.init.call(s,e,t),s.wrapper=s.element.addClass("k-button"),!s.element.attr("type")&&s.options.type&&s.element.attr("type",s.options.type),s._addClasses(),s.iconElement(),s._textElement()},options:{name:"HTMLButton",type:"button",icon:"",iconClass:"",spriteCssClass:"",imageUrl:"",size:"medium",rounded:"medium",fillMode:"solid",themeColor:"base",stylingOptions:["size","rounded","fillMode","themeColor"]},iconElement:function(){var n,i,o,a=this,l=a.element,r=a.options,d=r.icon,c=r.iconClass,p=r.spriteCssClass,u=r.imageUrl;(p||u||d||c)&&(o=!0,l.contents().filter((function(){return!(e(this).hasClass("k-sprite")||e(this).hasClass("k-icon")||e(this).hasClass("k-svg-icon")||e(this).hasClass("k-image"))})).each((function(e,n){(1==n.nodeType||3==n.nodeType&&t.trim(n.nodeValue).length>0)&&(o=!1)}))),o&&a.element.addClass("k-icon-button"),u?((i=l.children("img.k-image").first())[0]||(i=e('<img alt="icon" class="k-image" />').prependTo(l)),i.attr("src",u),i.addClass(s)):d||c?((n=l.children("span.k-icon, span.k-svg-icon").first())[0]?t.ui.icon(n,{icon:d,iconClass:c}):n=e(t.ui.icon({icon:d,iconClass:c})).prependTo(l),n.addClass(s)):p&&((n=l.children("span.k-sprite").first())[0]||(n=e('<span class="k-sprite"></span>').prependTo(l)),n.addClass(p+" "+s))},_textElement:function(){this.element.contents().filter((function(){return!(e(this).hasClass(s)||e(this).hasClass("k-sprite")||e(this).hasClass("k-icon")||e(this).hasClass("k-image"))})).each((function(e,n){if(1==n.nodeType||3==n.nodeType&&t.trim(n.nodeValue).length>0){if(3===n.nodeType){var s=document.createElement("span");n.parentNode.insertBefore(s,n),s.appendChild(n),n=s}n.classList.add("k-button-text")}}))}});e.extend(t.html,{renderButton:function(t,n){return(undefined===arguments[0]||e.isPlainObject(arguments[0]))&&(n=t,t=e("<button></button>")),new i(t,n).html()},HTMLButton:i}),t.cssProperties.registerPrefix("HTMLButton","k-button-"),t.cssProperties.registerValues("HTMLButton",[{prop:"fillMode",values:t.cssProperties.fillModeValues.concat(["link","clear"])},{prop:"rounded",values:t.cssProperties.roundedValues.concat([["full","full"]])}])}(window.kendo.jQuery);var kendo$1=kendo;export{__meta__,kendo$1 as default};
//# sourceMappingURL=kendo.html.button.js.map
