/**
 * Kendo UI v2024.4.1112 (http://www.telerik.com/kendo-ui)
 * Copyright 2024 Progress Software Corporation and/or one of its subsidiaries or affiliates. All rights reserved.
 *
 * Kendo UI commercial licenses may be obtained at
 * http://www.telerik.com/purchase/license-agreement/kendo-ui-complete
 * If you do not own a commercial license, this file shall be governed by the trial license terms.
 */
const __meta__={id:"dropdowns-loader.chunk",name:"DropdownsLoaderChunk",category:"web",description:"A reusable outputed chunk of code",depends:[],hidden:!0,chunk:!0};let $=kendo.jQuery;const LOADING="k-loading",LOADER="k-icon k-i-loading k-input-loading-icon",SELECTOR="k-input-inner",INPUT_VALUES="k-input-values",ARIA_BUSY="aria-busy";function initLoader(){const e=this,s=$("<span></span>").addClass(LOADER).attr("role","presentation");e._loading=s,e._showBusy=showBusy.bind(e),e._hideBusy=hideBusy.bind(e),e._toggleLoader=toggleLoader.bind(e),e._showBusyHandler=showBusyHandler.bind(e)}function toggleLoader(e){const s=this,o=s.wrapper.hasClass(LOADING),n=s.wrapper.find(`.${INPUT_VALUES}`),t="multiselect"===s.options.name.toLowerCase();if(s._loading)if(e&&!o)if(s.wrapper.addClass(LOADING),s._suffixContainer){const e=s.wrapper.find(".k-input-separator");$(e[e.length-1]).before(s._loading)}else if(s._arrow)s._arrow.before(s._loading);else if(n.length>0&&t)s._loading.insertAfter(n);else{const e=s.element.hasClass(SELECTOR)?s.element:s.wrapper.find(`.${SELECTOR}`);s._loading.insertAfter(e)}else o&&(s.wrapper.removeClass(LOADING),s._loading.remove())}function showBusyHandler(){const e=this;if(e._focused)e._focused.attr(ARIA_BUSY,!0);else{(e.element.hasClass(SELECTOR)?e.element:e.wrapper.find(`.${SELECTOR}`)).attr(ARIA_BUSY,!0)}e._toggleLoader(!0),e._hideClear()}function showBusy(e){const s=this;e&&e.isDefaultPrevented()||(s._request=!0,s._busy||(s._busy=setTimeout(s._showBusyHandler,100)))}function hideBusy(){const e=this;if(clearTimeout(e._busy),e._toggleLoader(!1),e._busy=null,e._request&&(e._request=!1),e._focused)e._focused.attr(ARIA_BUSY,!1);else{(e.element.hasClass(SELECTOR)?e.element:e.wrapper.find(`.${SELECTOR}`)).attr(ARIA_BUSY,!0)}e._toggleCloseVisibility?e._toggleCloseVisibility():e._showClear()}export{initLoader as i};export{__meta__};
//# sourceMappingURL=kendo.dropdowns-loader.chunk.js.map
